package signaling

import (
	"encoding/json"
	"strings"
	"testing"

	pionwebrtc "github.com/pion/webrtc/v3"
	"github.com/sajadbayatani/slive/internal/domain"
	webrtc "github.com/sajadbayatani/slive/internal/webrtc"
)

// TestHandleMessageIgnoresUnknownType pins the dispatch-table default branch:
// unknown message types are silently ignored — no error surfaces to the
// caller and nothing is written back onto the connection.
func TestHandleMessageIgnoresUnknownType(t *testing.T) {
	h := newTestHandler()
	room, participant := joinParticipant(t, h, "dispatch-room", "p-dispatch")

	conn := newHeadlessConn("p-dispatch", "dispatch-room")

	for _, unknown := range []MessageType{"bogus", "", "webrtc:bogus"} {
		if err := h.handleMessage(conn, room, participant, &Message{Type: unknown}); err != nil {
			t.Errorf("handleMessage(%q) = %v, want nil", unknown, err)
		}
	}
	if msgs := drainMessages(conn); len(msgs) != 0 {
		t.Errorf("unexpected responses for unknown types: %+v", msgs)
	}
}

// TestHandleOfferGeneratesRealAnswerThroughTargetPC drives the SFU-style
// happy end-to-end signaling path over the REAL dispatch table: a genuine
// pion offer (with media section and ICE credentials) is installed on the
// TARGET participant's peer connection, the server answers on its behalf,
// and the generated answer flows back to the source connection.
func TestHandleOfferGeneratesRealAnswerThroughTargetPC(t *testing.T) {
	h := newTestHandler()
	room, source := joinParticipant(t, h, "offer-room", "p-source")
	target := domain.NewParticipant("p-target", "User p-target")
	if err := room.Join(target); err != nil {
		t.Fatalf("Join(target): %v", err)
	}

	// The target owns the server-side peer connection that must answer.
	targetPC, err := h.ensurePeerConnection(target, channelSender(make(chan string, 8)))
	if err != nil {
		t.Fatalf("ensurePeerConnection(target): %v", err)
	}

	// Produce a genuine offer from an independent offline peer connection,
	// exactly like a browser client would.
	offererPC, err := webrtc.NewPeerConnection(newTestPeerConnectionConfig(), domain.NewParticipant("offerer", "Offerer"), nil)
	if err != nil {
		t.Fatalf("NewPeerConnection(offerer): %v", err)
	}
	defer func() { _ = offererPC.Close() }()
	if _, err := offererPC.PionPeerConnection().AddTransceiverFromKind(pionwebrtc.RTPCodecTypeAudio); err != nil {
		t.Fatalf("AddTransceiverFromKind: %v", err)
	}
	offer, err := offererPC.CreateOffer()
	if err != nil {
		t.Fatalf("CreateOffer: %v", err)
	}

	payload, err := json.Marshal(OfferRequest{
		RoomID:              room.ID(),
		ParticipantID:       source.ID(),
		TargetParticipantID: target.ID(),
		SDP:                 offer.SDP(),
	})
	if err != nil {
		t.Fatalf("marshal offer request: %v", err)
	}

	sourceConn := newHeadlessConn(source.ID(), room.ID())
	if err := h.handleMessage(sourceConn, room, source, &Message{
		Type: MessageTypeOffer,
		Data: payload,
	}); err != nil {
		t.Fatalf("handleMessage(offer): %v", err)
	}

	messages := drainMessages(sourceConn)
	if len(messages) != 1 {
		t.Fatalf("expected exactly one response, got %d: %+v", len(messages), messages)
	}
	if messages[0].Type != MessageTypeAnswer {
		t.Fatalf("response type = %s, want %s", messages[0].Type, MessageTypeAnswer)
	}

	var notification AnswerNotification
	if err := messages[0].UnmarshalData(&notification); err != nil {
		t.Fatalf("unmarshal answer notification: %v", err)
	}
	if notification.SourceParticipantID != target.ID() {
		t.Errorf("source_participant_id = %q, want the target %q",
			notification.SourceParticipantID, target.ID())
	}
	for _, fragment := range []string{"m=audio", "a=ice-ufrag"} {
		if !strings.Contains(notification.SDP, fragment) {
			t.Errorf("answer SDP missing %q:\n%s", fragment, notification.SDP)
		}
	}

	// The answer must have been generated by the target peer connection: its
	// local description is now a real answer and the offer became its remote
	// description.
	localDesc := targetPC.PionPeerConnection().LocalDescription()
	if localDesc == nil || localDesc.Type != pionwebrtc.SDPTypeAnswer {
		t.Fatalf("target local description = %+v, want an answer", localDesc)
	}
	if !strings.Contains(localDesc.SDP, "m=audio") {
		t.Errorf("target local answer missing audio m-line:\n%s", localDesc.SDP)
	}

	// ICE routing happy path: with the offer installed on the target, a
	// well-formed candidate must be accepted silently — no error response
	// reaches the source connection (error paths are covered elsewhere).
	icePayload, err := json.Marshal(ICECandidateRequest{
		RoomID:              room.ID(),
		ParticipantID:       source.ID(),
		TargetParticipantID: target.ID(),
		Candidate:           "candidate:842163049 1 udp 1677729535 192.0.2.1 31102 typ srflx",
		SDPMid:              "0",
		SDPMLineIndex:       0,
	})
	if err != nil {
		t.Fatalf("marshal ice request: %v", err)
	}
	if err := h.handleMessage(sourceConn, room, source, &Message{
		Type: MessageTypeICECandidate,
		Data: icePayload,
	}); err != nil {
		t.Fatalf("handleMessage(ice-candidate): %v", err)
	}
	for _, m := range drainMessages(sourceConn) {
		if m.Type == MessageTypeError {
			var resp ErrorResponse
			if err := m.UnmarshalData(&resp); err != nil {
				t.Fatalf("unmarshal unexpected error response: %v", err)
			}
			t.Errorf("happy-path ICE produced an error response: %+v", resp)
		}
	}
}
